# Site settings
title: 海风如歌
email: haifuncn@gmail.com
description: "haifun "
baseurl: ""
url: "http://haifun.github.io/"
twitter_username: haifuncn
github_username:  haifun

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title/
